/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("StocksApi", () => {
  let instance: api.StocksApi
  beforeEach(function() {
    instance = new api.StocksApi(config)
  });

  test("stocksAddPost", () => {
    const body: api.ManipulationRequest = undefined
    return expect(instance.stocksAddPost(body, {})).resolves.toBe(null)
  })
  test("stocksGetListPost", () => {
    const body: api.ListRequest = undefined
    return expect(instance.stocksGetListPost(body, {})).resolves.toBe(null)
  })
  test("stocksRemoveDelete", () => {
    const body: api.ManipulationRequest = undefined
    return expect(instance.stocksRemoveDelete(body, {})).resolves.toBe(null)
  })
})

