/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("IdentityManagementApi", () => {
  let instance: api.IdentityManagementApi
  beforeEach(function() {
    instance = new api.IdentityManagementApi(config)
  });

  test("userCheckTokenGet", () => {
    return expect(instance.userCheckTokenGet({})).resolves.toBe(null)
  })
  test("userDeleteDelete", () => {
    const body: api.DeleteRequest = undefined
    return expect(instance.userDeleteDelete(body, {})).resolves.toBe(null)
  })
  test("userLoginPost", () => {
    const body: api.LoginRequest = undefined
    return expect(instance.userLoginPost(body, {})).resolves.toBe(null)
  })
  test("userRegisterPost", () => {
    const body: api.RegisterRequest = undefined
    return expect(instance.userRegisterPost(body, {})).resolves.toBe(null)
  })
  test("userUpdatePatch", () => {
    const body: api.UpdateRequest = undefined
    return expect(instance.userUpdatePatch(body, {})).resolves.toBe(null)
  })
})

